### ISSUE TITLE
Error: exception 'InvalidArgumentException' with message ''rich_title'

### ISSUE THREAD

**Issue by DBinaghi** [omeka/theme-foundation#26]
When choosing Media Display = List, the following error occurs: 
`exception 'InvalidArgumentException' with message ''rich_title' non è valido come valore speciale.' in /web/htdocs/www.bitoteko.it/home/application/libraries/Omeka/Record/AbstractRecord.php:351`
```
Stack trace:
#0 /web/htdocs/www.bitoteko.it/home/application/models/File.php(151): Omeka_Record_AbstractRecord->getProperty('rich_title')
#1 /web/htdocs/www.bitoteko.it/home/application/views/helpers/Metadata.php(169): File->getProperty('rich_title')
#2 /web/htdocs/www.bitoteko.it/home/application/views/helpers/Metadata.php(144): Omeka_View_Helper_Metadata->_getRecordMetadata(Object(File), 'rich_title')
#3 /web/htdocs/www.bitoteko.it/home/application/views/helpers/Metadata.php(73): Omeka_View_Helper_Metadata->_getText(Object(File), 'rich_title')
#4 [internal function]: Omeka_View_Helper_Metadata->metadata(Object(File), 'rich_title', Array)
#5 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#6 /web/htdocs/www.bitoteko.it/home/application/libraries/globals.php(2042): Zend_View_Abstract->__call('metadata', Array)
#7 /web/htdocs/www.bitoteko.it/home/application/libraries/globals.php(2042): Omeka_View->metadata(Object(File), 'rich_title', Array)
#8 /web/htdocs/www.bitoteko.it/home/themes/foundation/functions.php(167): metadata(Object(File), 'rich_title', Array)
#9 /web/htdocs/www.bitoteko.it/home/themes/foundation/items/show.php(21): foundation_display_attached_media(Object(Item))
#10 /web/htdocs/www.bitoteko.it/home/application/libraries/Omeka/View.php(114): include('/web/htdocs/www...')
#11 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/web/htdocs/www...')
#12 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('items/show.php')
#13 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('items/show.php', NULL)
#14 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#15 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#16 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#18 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#19 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#20 /web/htdocs/www.bitoteko.it/home/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#21 /web/htdocs/www.bitoteko.it/home/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#22 /web/htdocs/www.bitoteko.it/home/index.php(23): Omeka_Application->run()
#23 {main}
```

**Comment by kimisgold** [comment]
The next release of Omeka Classic will introduce widespread use of rich titles for items. Upgrading to that release should fix this issue.

**Comment by DBinaghi** [comment]
But there should be a safe fallback for previous versions, if theme is installable on them.
